// <auto-generated />
using AfricaTransfer.CoreLib.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AfricaTransfer.CoreLib.Migrations
{
    [DbContext(typeof(AfricaTransferContext))]
    [Migration("20180421085853_AddPhoneCredit")]
    partial class AddPhoneCredit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.AuthModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("AuthModel");
                });

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.PhoneCredit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthModelID");

                    b.Property<float>("Credit");

                    b.HasKey("ID");

                    b.HasIndex("AuthModelID");

                    b.ToTable("PhoneCredit");
                });

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.PhoneCredit", b =>
                {
                    b.HasOne("AfricaTransfer.CoreLib.Models.AuthModel", "AuthModel")
                        .WithMany()
                        .HasForeignKey("AuthModelID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
