// <auto-generated />
using AfricaTransfer.CoreLib.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AfricaTransfer.CoreLib.Migrations
{
    [DbContext(typeof(AfricaTransferContext))]
    [Migration("20180421115200_AddOrderStatus")]
    partial class AddOrderStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.AuthModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("AuthModel");
                });

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.BankTransaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Ammount");

                    b.Property<int>("DestinationAuthModelID");

                    b.Property<int?>("SourceBankID");

                    b.HasKey("ID");

                    b.HasIndex("DestinationAuthModelID");

                    b.ToTable("BankTransaction");
                });

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.MobileTransaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Ammount");

                    b.Property<int>("DestinationAuthModelID");

                    b.Property<int?>("DestinationModelAuthModelID");

                    b.Property<int>("SourceAuthModelID");

                    b.HasKey("ID");

                    b.HasIndex("DestinationModelAuthModelID");

                    b.HasIndex("SourceAuthModelID");

                    b.ToTable("MobileTransaction");
                });

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BuyerID");

                    b.Property<int>("SellerID");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("SellerID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.OrderLine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("OrderID");

                    b.Property<int>("ProductID");

                    b.Property<float>("ProductPrice");

                    b.Property<float>("Quantity");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderLine");
                });

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.PhoneCredit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthModelID");

                    b.Property<float>("Credit");

                    b.HasKey("ID");

                    b.HasIndex("AuthModelID");

                    b.ToTable("PhoneCredit");
                });

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<float>("Price");

                    b.HasKey("ID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.BankTransaction", b =>
                {
                    b.HasOne("AfricaTransfer.CoreLib.Models.AuthModel", "DestinationAuthModel")
                        .WithMany()
                        .HasForeignKey("DestinationAuthModelID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.MobileTransaction", b =>
                {
                    b.HasOne("AfricaTransfer.CoreLib.Models.AuthModel", "DestinationModelAuthModel")
                        .WithMany()
                        .HasForeignKey("DestinationModelAuthModelID");

                    b.HasOne("AfricaTransfer.CoreLib.Models.AuthModel", "SourceAuthModel")
                        .WithMany()
                        .HasForeignKey("SourceAuthModelID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.Order", b =>
                {
                    b.HasOne("AfricaTransfer.CoreLib.Models.AuthModel", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AfricaTransfer.CoreLib.Models.AuthModel", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.OrderLine", b =>
                {
                    b.HasOne("AfricaTransfer.CoreLib.Models.Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AfricaTransfer.CoreLib.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AfricaTransfer.CoreLib.Models.PhoneCredit", b =>
                {
                    b.HasOne("AfricaTransfer.CoreLib.Models.AuthModel", "AuthModel")
                        .WithMany()
                        .HasForeignKey("AuthModelID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
